### ISSUE TITLE
type and enum aren't handle at all in the generated factory

### ISSUE THREAD

**Issue by maxime4000** [toyamarinyon/prisma-factory-generator#19]
Great idea for a generator, it's clearly not finish, but does a good job for what it does. 

We are using mongodb, because mongodb is a document database, we use a mix of model/type/enum. We have nested data in our model and this is forgotten in the generator.
So example : 
```prisma
type UserInfo {
  firstName String
  lastName String
}

enum UserStatus {
ACTIVE
DELETED
...
}

model User {
  id                String             @id @default(auto()) @map("_id") @db.ObjectId
  email             String             @unique
  userInfo          UserInfo
  status            UserStatus
}
```
If you call :
```ts
const user = createUser(); 
const user2 = createUser({data: inputsForUser()}); 
```
This will fail because userInfo is not defined, but required. inputsForUser() should be able to generate UserInfo type, but for now it ain't. 
This is what inputsForUser look like :
```ts
function inputsForUser() {
  return {
    email: faker.internet.email(),
  };
}
```
This is what I would have expect
```ts
const UserStatusEnum = ["ACTIVE", "DELETED", ...];
function inputsForUser() {
  return {
    email: faker.internet.email(),
    status: faker.random.arrayElement(UserStatusEnum),
    userInfo: {
      firstName: faker.name.title(),
      lastName: faker.name.title(),
    }
  };
}
```

I think it's a long shot hoping this will be added, looking at the git history, but in case this get considered. Thanks for your time :)

**Comment by luisrudge** [comment]
I fixed the enum part in #22
